source 'https://github.com/royhsu/chocolate-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
use_frameworks!

target 'Chocolate' do
	pod 'CHFoundation', '0.4.5'
end

target 'ChocolateTests' do
	pod 'CHFoundation', '0.4.5'
end

target 'ChocolateExamples' do
	pod 'CHFoundation', '0.4.5'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
