source 'https://github.com/royhsu/chocolate-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
use_frameworks!

target 'Chocolate' do
	pod 'CHFoundation', '0.2'
end

target 'ChocolateTests' do
	pod 'CHFoundation', '0.2'
end

target 'ChocolateExamples' do
	pod 'CHFoundation', '0.2'
	pod 'moa', '4.0.0'
end