platform :ios, "8.0"
use_frameworks!

#target 'TWKit' do
#	pod 'TWFoundation', :git => 'https://github.com/royhsu/swift-foundation.git', :branch => 'master', :commit => '28e8eb885c03b3e40a4fd6df9a150bcfcdb4c096'
#end

target 'TWKitExamples' do
	pod 'AlamofireImage', '2.4.0'
end

